- hosts: all
  gather_facts: no
  vars:
    ansible_host_key_checking: false
  tasks:
    - local_action: wait_for port=22 host="{{ ip }}" search_regex=OpenSSH delay=10

    - name: Update & Upgrade apt packages
      become: true
      become_method: sudo
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install Docker
      become: true
      become_method: sudo
      shell: |
        apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg \
          lsb-release
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo \
          "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io
      tags:
        - docker_install

    - name: Start Docker
      become: true
      become_method: sudo
      service:
        name: docker
        state: started
        enabled: yes
      tags:
        - docker_start

    - name: Download Gitlab Runner
      become: true
      become_method: sudo
      get_url:
        url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-arm64
        dest: /usr/local/bin/gitlab-runner
        mode: '0755'

    - name: Create Gitlab Runner User
      become: true
      become_method: sudo
      user:
        name: gitlab-runner
        shell: /bin/bash
        state: present
        createhome: yes

    - name: Install Gitlab Runner
      become: true
      become_method: sudo
      command: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
      args:
        creates: /etc/gitlab-runner

    - name: Start Gitlab Runner
      become: true
      become_method: sudo
      service:
        name: gitlab-runner
        state: started
        enabled: yes

    - name: Register Gitlab Runner
      become: true
      become_method: sudo
      command: gitlab-runner register --non-interactive --url https://gitlab-2.gaussb.io/ --registration-token GR1348941UxXw-BtKd_j7hCjrrb51 --executor docker --docker-image alpine:latest --description "Docker Runner" --tag-list "docker,aws" --run-untagged --locked="false"
      register: register_runner
